pre-commit hook validate that content is up-to-date

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,12 +1,23 @@
 #!/bin/sh
 
-# Runs Prettier, ESLint and tsc on .ts, .tsx, .js, .md, .css and .json files. Prettier and ESLint only check the
+# Runs Prettier, ESLint and tsc on .ts, .tsx, .js, .md, .yml, .yaml, .css and .json files. Prettier and ESLint only check the
 # committed files, whereas tsc checks all project files, since it's not possible to run tsc on specific files while
 # obeying the tsconfig.json options (see https://github.com/microsoft/TypeScript/issues/27379 and
 # https://www.npmjs.com/package/tsc-files).
 # This hook always commits, even if errors are found. And it does not modify the files (ie it does not do `prettier
 # write`), it only checks if there is any issue and reports it.
 # Inspired by https://prettier.io/docs/en/precommit.html#option-6-shell-script
+
+# Validate that pre-commit and .git/hooks/pre-commit have the same content.
+# If content is not the same, do not commit.
+diff pre-commit .git/hooks/pre-commit > /dev/null
+if [[ $? == 1 ]]
+then
+  echo "Error: pre-commit and .git/hooks/pre-commit have different content."
+  echo "Commit aborted."
+  echo "To fix this run: cp pre-commit .git/hooks"
+  exit 1
+fi
 
 get_staged_files() {
   ALL_FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g' | awk '/\.ts$|\.tsx$|\.js$|\.md|\.yml|\.yaml|\.css|\.json/')
